name: Build and Release CV

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permission:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11
        
      - name: Build PDF
        run: |
          VERSION="v${GITHUB_RUN_NUMBER}"
          FILE_NAME="dan-nicholls-cv-${VERSION}.pdf"
          mkdir -p build
          nix-shell --pure --run "xelatex -interaction=nonstopmode -output-directory=build cv.tex"
          mv build/cv.pdf build/dan-nicholls-cv-${VERSION}.pdf
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "FILE_NAME=${FILE_NAME}" >> $GITHUB_ENV

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: "CV ${{ env.VERSION }}"
          files: build/${{ env.FILE_NAME }}"
