name: Build and Release CV

on:
  push:
    paths:
      - '**.tex'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11
        
      - name: Build PDF
        run: |
          mkdir -p build
          nix-shell --pure --run "xelatex -interaction=nonstopmode -output-directory=build cv.tex"

      - name: Prepare PDF for upload
        run: |
          ls -la
          ls build/ -la
          VERSION="v${GITHUB_RUN_NUMBER}"
          FILE_NAME="dan-nicholls-cv-${VERSION}.pdf"

          mv build/cv.pdf build/${FILE_NAME}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "FILE_NAME=${FILE_NAME}" >> $GITHUB_ENV

      - name: Upload PDF artifact
        uses: actions/upload-artifact@4
        with:
          name: ${{ env.FILE_NAME }}
          path: build/${{ env.FILE_NAME }}

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          files: build/${{ env.FILE_NAME }}"
          draft: true
